"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var num1 = 111;
var num2 = 10;
var ans1 = num1 + num2;
var ans2 = num1 - num2;
var ans3 = num1 * num2;
var ans4 = num1 / num2;
var ans5 = num1 % num2;
var ans6 = Math.pow(num1, num2);
console.log(ans1);
console.log(ans2);
console.log(ans3);
console.log(ans4);
console.log(ans5);
console.log(ans6);
